POST https://localhost:7091/user/login
Content-Type: application/json

{ "Username" : "rajipkanxo01", "Password" : "20602059" }

###

GET https://localhost:7091/forum
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI0ZjA5MzMzMi1jNjAyLTRlYTItYmEzMy0xNDA5N2Y3ZmI0MjkiLCJpYXQiOiI0LzYvMjAyMyA5OjQxOjQ0IFBNIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InJhamlwMTIiLCJleHAiOjE2ODA4MjA5MDQsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZVNlcnZlckFwcCJ9.KmY8cOsCzsDSnbP8s-LDS2h3dV7PwNUpLWxnKhXXppZ9SSuKBvqyjWQj63Imv5ud9FoKU0-U4piRghJqe2n91Q


###

POST https://localhost:7091/post/create
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiIyMWM1OTM4ZS0yMjY5LTQyNTgtODQ5Ny03OGY3NTRhNWEzNjQiLCJpYXQiOiI0LzcvMjAyMyAyOjAwOjU3IFBNIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InJhamlwa2FueG8wMSIsImV4cCI6MTY4MDg3OTY1NywiaXNzIjoiSldUQXV0aGVudGljYXRpb25TZXJ2ZXIiLCJhdWQiOiJKV1RTZXJ2aWNlU2VydmVyQXBwIn0.bx3SYs3QEHfRheWZWBHMU6ekUHDOrpNzmymIsPwzkI50tuWvEYoXAh4Rj4OQp_oyfyrCrMts5eBztTsc74S6iw
Content-Type: application/json


###
GET https://localhost:7091/Forum/1

###
#get all post in a forum
GET https://localhost:7091/Post/forum/1


###
#get specific post according to id
GET https://localhost:7091/Post/viewpost/2

###
POST https://localhost:7091/Comment/create
Content-Type: application/json

{
  "CommentBody": "This is a sample comment.",
  "PostedByUser": "John Doe"
}

